# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gits, Gist and Musings
email: rpfilomeno@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Know more about Roger Filomeno. My work, my thoughts, my rants.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rpfilomeno.github.io" # the base hostname & protocol for your site
twitter_username: godie
github_username:  rpfilomeno
comments: true

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor
- serve.cmd
- build.cmd

# Build settings
markdown: kramdown


